### ISSUE TITLE
Commit gemfile.lock and remove it from .gitignore

### ISSUE THREAD

**Issue by ytbryan** [vueonrails/vueonrails#16]
If anyone wants to take first stab cc @m5o @rlafranchi

**Comment by m5o** [comment]
> When developing a gem […] Do not check your `Gemfile.lock` into version control

📖 https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

**Comment by ytbryan** [comment]
🙏 Thanks Matt
