### ISSUE TITLE
link is broken

### ISSUE THREAD

**Issue by williamhatch** [vueonrails/vueonrails#25]
https://github.com/vueonrails/vueonrails/blob/master/docs

**Comment by m5o** [comment]
Thank you @williamhatch 

@ytbryan could you please check, probably some leftover:
https://github.com/vueonrails/vueonrails/blame/master/README.md#L52

**Comment by ytbryan** [comment]
The open-source Vue on Rails handbook will be  released together with the paid [Vue on Rails book](https://vueonrails.com). The paid book will include premium content and exclusive tutorials. I don't have a release date yet. 

As of now, please submit or use Github issues to ask questions or raise problems. 

But If anyone wants to send a PR for the docs, I will be happy to review too.
