### ISSUE TITLE
This gem supports SSR?

### ISSUE THREAD

**Issue by almirpask** [vueonrails/vueonrails#28]
This gem support server side rendering with vue components?

**Comment by ytbryan** [comment]
I'm working hard on SSR. Need more time.

**Comment by ytbryan** [comment]
Yes https://github.com/vueonrails/vueonrails/commit/771ed5f5431104d4bde649c4003748cde0b8054c


### Assuming you setup vue on rails  manually and  correctly. 

At Gemfile and `bundle
```
gem 'vueonrails'
```

Finally, run `rails vue:setup`. 

Alternatively, use app template to do everything above automatically
`rails new app -m http://vueonrails.com/vue -d postgresql`

### Configure SSR automatically

```
rails vue:ssr
```

### generate new component

```
rails generate vue <NAME> --ssr
```
